2020-08-17 00:39:12,659 INFO werkzeug MainThread :  * Running on http://localhost:5000/ (Press CTRL+C to quit)
2020-08-17 00:39:16,472 INFO app Thread-1 : Number link got : 1
2020-08-17 00:39:16,473 ERROR app Thread-1 : Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 84, in getLink
    file_name_requestted.remove(file_name)
ValueError: list.remove(x): x not in list
2020-08-17 00:39:16,475 INFO werkzeug Thread-1 : 127.0.0.1 - - [17/Aug/2020 00:39:16] "[1m[35mPOST / HTTP/1.1[0m" 500 -
